version: '3.4'

services:
    db:
        image: mariadb:10.6
        container_name: defichain
        volumes:
            - defichain:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=ROOT
            - MYSQL_DATABASE=defichain
            - MYSQL_USER=defichain
            - MYSQL_PASSWORD=defichain
        ports:
          - 3306:3306

    adminer:
      image: adminer
      ports:
        - 8081:8080

volumes:
  defichain:
